modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Name%20Tag%20Tweaks"
logoFile="icon.png"

[[mods]]
modId="nametagtweaks"
version="3.2"
displayName="Name Tag Tweaks"
displayURL="https://serilum.com/mod/name-tag-tweaks"
authors="Rick South"
description='''Adds name tag crafting recipe, /nametag command, and named entities drop their name tag on death.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.nametagtweaks]]
    modId="collective"
    type="required"
    mandatory=true
    versionRange="[7.21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.nametagtweaks]]
    modId="minecraft"
    type="required"
    mandatory=true
    versionRange="[1.20.2]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "nametagtweaks_neoforge.mixins.json"